# This is a basic workflow to help you get started with Actions

name: deploy test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: deploy
        env:
          SECRET_KEY: ${{ secrets.STG_SECRET_KEY }}
          USER: ${{ secrets.STG_USER }}
          HOST: ${{ secrets.STG_HOST }}
        run: |
          # 秘密鍵にファイル名secret_keyをつける
          echo "$SECRET_KEY" > secret_key
          # パー民ッションの変更
          chmod 600 secret_key
          # ローカルの情報確認
          ls -lrt
          # ssh接続
          # ssh -oStrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "ls -lrt"
          # ssh接続してrsyncのdry-runをする
          rsync -ahbvcO --delete --exclude-from .rsyncignore -e "ssh -i secret_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./packages/ ${USER}@${HOST}:/home/ec2-user/test/
          
